### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by Dan69UwU** [noah-owens/Character-Forge#27]
![2022-07-16 14_48_38-Impostazioni](https://user-images.githubusercontent.com/109420154/179355579-34fdcfec-4b15-421f-bf15-e396b286b2b2.png)
gradle is stuck at this point and i dont know what to do

**Comment by noah-owens** [comment]
Hey, I'm so sorry about that! I haven't been keeping up with this project and right now I don't think that the code on either branch will run correctly. I will get that fixed asap. Sorry for any distress that might have caused!

**Comment by noah-owens** [comment]
Should be resolved now!
